checks:
    python:
        code_rating: true
        duplicate_code: true
filter:
    excluded_paths:
        - 'tests/*'

build:
    environment:
        python: 3.4.1
    tests:
        override:
            -
                command: 'coverage run -m unittest'
                coverage:
                    file: '.coverage'
                    config: '.coveragerc'
                    format: 'py-cc'