checks:
    python:
        code_rating: true
        duplicate_code: true
filter:
    excluded_paths:
        - 'tests/*'

build:
    environment:
        python: 3.4.1
    dependencies:
        before:
            - pip install coverage
    tests:
        override:
            -
                command: 'coverage run -m unittest'
                coverage:
                    file: '.coverage'
                    format: 'py-cc'
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override: [py-scrutinizer-run]